services:
  - type: web
    name: TECHNOW
    env: static
    staticPublishPath: dist/TECHNOW
    buildCommand: npm install && npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html